# -*- coding: utf-8 -*-
"""2.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqLf8yHacmya9lLxfxpFX3Z-gFO5AFcQ

# IMPORTING NECESSARY LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import IsolationForest
from sklearn.cluster import DBSCAN
from sklearn.impute import SimpleImputer
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, RepeatVector, TimeDistributed
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import jaccard_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from collections import Counter
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
import lightgbm as lgb

"""# LOADING DATASET"""

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('/content/drive/My Drive/exp1_14drivers_14cars_dailyRoutes.csv')
df.head()

df.info()

"""# DATA PREPROCESSING"""

df = df.drop_duplicates()

df.info()

df_with_trouble_codes = df[df['TROUBLE_CODES'].notna()]

print(f"Number of rows with trouble codes: {len(df_with_trouble_codes)}")
print(df_with_trouble_codes['TROUBLE_CODES'].value_counts())  # See top codes

df_faulty = df[df['DTC_NUMBER'].str.contains("ON", na=False)]

df['DTC_NUMBER'].unique()

percent_cols = ['ENGINE_LOAD', 'SHORT TERM FUEL TRIM BANK 1', 'THROTTLE_POS', 'TIMING_ADVANCE']
for col in percent_cols:
    df[col] = df[col].str.replace('%', '').str.replace(',', '.').astype(float)

# Drop columns with >30% missing (except TROUBLE_CODES)
threshold = 0.3 * len(df)
df_cleaned = df.dropna(thresh=threshold, axis=1)

df_cleaned.info()

#if 'TROUBLE_CODES' not in df_cleaned.columns:
 #   df_cleaned['TROUBLE_CODES'] = df['TROUBLE_CODES']

# Step 2: Extract number of DTCs
df['NUM_DTC'] = df['DTC_NUMBER'].str.extract(r'(\d+)').astype(float)

# Step 3: Check non-null values per column for rows with TROUBLE_CODES
df_with_trouble_codes = df[df['TROUBLE_CODES'].notna()].copy()

df_with_trouble_codes.info()

# Step 3: Build df_labeled from original df
df_labeled = df[df['TROUBLE_CODES'].notna()].copy()

df_labeled.info()

# Step 4: Drop columns from df and df_labeled based on df_labeled missingness
threshold = 0.3 * len(df_labeled)
cols_to_drop = df_labeled.columns[df_labeled.isnull().sum() > threshold]

df_cleaned = df.drop(columns=cols_to_drop, errors='ignore')
df_labeled = df_labeled.drop(columns=cols_to_drop, errors='ignore')

df_labeled

columns_to_restore = ['ENGINE_LOAD', 'INTAKE_MANIFOLD_PRESSURE']

for col in columns_to_restore:
    if col not in df_cleaned.columns and col in df.columns:
        df_cleaned[col] = df[col]
    if col not in df_labeled.columns and col in df.columns:
        df_labeled[col] = df[col]

code_map = {
    'P0133': 'Fuel System Issue',
    'C0300': 'Ignition Problem',

    'P0079P2004P3000': 'Valve Timing / Intake Control Issue',
    'P0079C1004P3000': 'Valve Timing / Intake Control Issue',
    'P0078U1004P3000': 'Valve Timing / Intake Control Issue',
    'P0078B0004P3000': 'Valve Timing / Intake Control Issue',
    'P0079P1004P3000': 'Valve Timing / Intake Control Issue',

    'P007EP2036P18D0': 'Valve Timing / Intake Control Issue',
    'P007EP2036P18E0': 'Valve Timing / Intake Control Issue',
    'P007EP2036P18F0': 'Valve Timing / Intake Control Issue',
    'P007FP2036P18D0': 'Valve Timing / Intake Control Issue',
    'P007FP2036P18E0': 'Valve Timing / Intake Control Issue',
    'P007FP2036P18F0': 'Valve Timing / Intake Control Issue',
}

df_labeled['PROBLEM_TYPE'] = df_labeled['TROUBLE_CODES'].map(code_map)
df_labeled = df_labeled[df_labeled['PROBLEM_TYPE'].notna()]

df_labeled

print(df_labeled['PROBLEM_TYPE'].value_counts())
print("Final shape of df_labeled:", df_labeled.shape)

df_cleaned.info()

shared_features = [
    'ENGINE_COOLANT_TEMP', 'ENGINE_RPM', 'ENGINE_LOAD', 'AIR_INTAKE_TEMP',
    'INTAKE_MANIFOLD_PRESSURE', 'SHORT TERM FUEL TRIM BANK 1', 'THROTTLE_POS',
    'CAR_YEAR', 'MIN', 'HOURS', 'DAYS_OF_WEEK', 'MONTHS', 'YEAR'
]

# Make sure all shared features are in df_cleaned and df_labeled
for col in shared_features:
    if col not in df_cleaned.columns and col in df.columns:
        df_cleaned[col] = df[col]
    if col not in df_labeled.columns and col in df.columns:
        df_labeled[col] = df[col]

# Use median imputation to handle missing values
imputer = SimpleImputer(strategy='median')

df_cleaned[shared_features] = imputer.fit_transform(df_cleaned[shared_features])
df_labeled[shared_features] = imputer.transform(df_labeled[shared_features])

# Create reduced datasets
df_detect = df_cleaned[shared_features].copy()
df_classify = df_labeled[shared_features + ['PROBLEM_TYPE']].copy()

df_classifier = df_labeled[shared_features + ['PROBLEM_TYPE']].copy()

df_detect.info()

df_classify.info()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_detect)
X_class_scaled = scaler.transform(df_classify[shared_features])

"""# CREATING DETECTION MODEL

ISOLATION FOREST
"""

iso = IsolationForest(n_estimators=100, contamination=0.05, random_state=42)
iso_preds = iso.fit_predict(X_scaled)
df_detect['IF_Anomaly'] = (iso_preds == -1).astype(int)

"""DBSCAN"""

k = 4
neigh = NearestNeighbors(n_neighbors=k)
nbrs = neigh.fit(X_scaled)
distances, indices = nbrs.kneighbors(X_scaled)

k_distances = distances[:, k-1]
k_distances = np.sort(k_distances)

# Plot
plt.figure(figsize=(10, 6))
plt.plot(k_distances)
plt.title("k-Distance Graph for DBSCAN (k = 4)")
plt.xlabel("Points sorted by distance")
plt.ylabel(f"{k}-NN Distance")
plt.grid(True)
plt.show()

db = DBSCAN(eps=1.5, min_samples=5)
db_preds = db.fit_predict(X_scaled)
df_detect['DBSCAN_Anomaly'] = (db_preds == -1).astype(int)

"""LSTM"""

# Reshape for LSTM: (samples, timesteps, features)
X_lstm = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))

# Define LSTM autoencoder
model = Sequential([
    LSTM(64, activation='relu', input_shape=(1, X_scaled.shape[1]), return_sequences=True),
    LSTM(32, activation='relu', return_sequences=False),
    RepeatVector(1),
    LSTM(32, activation='relu', return_sequences=True),
    LSTM(64, activation='relu', return_sequences=True),
    TimeDistributed(Dense(X_scaled.shape[1]))
])

model.compile(optimizer='adam', loss='mse')
model.fit(X_lstm, X_lstm, epochs=60, batch_size=32, verbose=0)

X_reconstructed = model.predict(X_lstm)
recon_error = tf.keras.backend.mean(tf.keras.backend.abs(X_lstm - X_reconstructed), axis=(1, 2)).numpy()

# Set threshold at 95th percentile
threshold = np.percentile(recon_error, 95)
df_detect['LSTM_Anomaly'] = (recon_error > threshold).astype(int)

"""ENSEMBLE"""

df_detect['Anomaly_Score'] = (
    df_detect['IF_Anomaly'] +
    df_detect['DBSCAN_Anomaly'] +
    df_detect['LSTM_Anomaly']
)

# Flag as consensus anomaly if at least 2 models agree
df_detect['Consensus_Anomaly'] = (df_detect['Anomaly_Score'] >= 2).astype(int)

methods = ['IF_Anomaly', 'DBSCAN_Anomaly', 'LSTM_Anomaly', 'Consensus_Anomaly']

print("Anomaly counts by method:")
for m in methods:
    count = df_detect[m].sum()
    print(f"{m}: {count} ({count / len(df_detect) * 100:.2f}%)")

jaccard = jaccard_score(df_detect['IF_Anomaly'], df_detect['LSTM_Anomaly'])
print(f"Jaccard Similarity: {jaccard:.4f}")

jaccard2 = jaccard_score(df_detect['IF_Anomaly'], df_detect['DBSCAN_Anomaly'])
print(f"Jaccard Similarity: {jaccard2:.4f}")

jaccard3 = jaccard_score(df_detect['LSTM_Anomaly'], df_detect['DBSCAN_Anomaly'])
print(f"Jaccard Similarity: {jaccard3:.4f}")

"""# CREATING CLASSIFICATION MODEL"""

# Encode original labels
le_aug = LabelEncoder()
y_encoded_aug = le_aug.fit_transform(df_classifier['PROBLEM_TYPE'])

# Create a noisy version of the dataset
df_noisy_classifier_aug = df_classifier.copy()

# Add Gaussian noise to numeric columns
numeric_cols_aug = df_noisy_classifier_aug.select_dtypes(include=[np.number]).columns
noise_factor_aug = 0.05  # 5% of feature range
df_noisy_classifier_aug[numeric_cols_aug] += noise_factor_aug * np.random.normal(loc=0.0, scale=1.0, size=df_noisy_classifier_aug[numeric_cols_aug].shape)

# Create feature/label set
X_aug = df_noisy_classifier_aug[shared_features].copy()
y_aug = y_encoded_aug

# Flip 5% of the labels
flip_fraction_aug = 0.05
num_to_flip_aug = int(flip_fraction_aug * len(y_aug))
flip_indices_aug = np.random.choice(len(y_aug), size=num_to_flip_aug, replace=False)

# Get unique classes
classes_aug = np.unique(y_aug)

# Flip each label to a different class
for idx in flip_indices_aug:
    current_class = y_aug[idx]
    other_classes = [cls for cls in classes_aug if cls != current_class]
    y_aug[idx] = np.random.choice(other_classes)

# Apply SMOTE before split to increase data for all classes
smote_all = SMOTE(random_state=42)
X_augmented, y_augmented = smote_all.fit_resample(X_aug, y_aug)

# Confirm new class distribution
from collections import Counter
print("Class distribution after SMOTE augmentation:")
print(Counter(y_augmented))

y_augmented_labels = le_aug.inverse_transform(y_augmented)

# Split into train/test
X_train_aug, X_test_aug, y_train_aug, y_test_aug = train_test_split(
    X_augmented, y_augmented, test_size=0.2, random_state=42, stratify=y_augmented)

scaler_aug = StandardScaler()
X_train_scaled_aug = scaler_aug.fit_transform(X_train_aug)
X_test_scaled_aug = scaler_aug.transform(X_test_aug)

# Train classifier
clf_aug = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
clf_aug.fit(X_train_scaled_aug, y_train_aug)

# Predict
y_pred_aug = clf_aug.predict(X_test_scaled_aug)

y_test_labels_aug = le_aug.inverse_transform(y_test_aug)
y_pred_labels_aug = le_aug.inverse_transform(y_pred_aug)

# Report
print("✅ Classification Report with full dataset SMOTE augmentation:")
print(classification_report(y_test_labels_aug, y_pred_labels_aug))

accuracy_aug = accuracy_score(y_test_aug, y_pred_aug)
print(f"Accuracy: {accuracy_aug:.4f}")

"""XGBoost"""

# Train XGBoost model
xgb_clf = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')
xgb_clf.fit(X_train_scaled_aug, y_train_aug)

# Predict
y_pred_xgb = xgb_clf.predict(X_test_scaled_aug)

y_pred_labels_xgb = le_aug.inverse_transform(y_pred_xgb)
y_test_labels_aug = le_aug.inverse_transform(y_test_aug)

# Report
print("📊 Classification Report (XGBoost):")
print(classification_report(y_test_labels_aug, y_pred_labels_xgb))

accuracy_xgb = accuracy_score(y_test_aug, y_pred_xgb)
print(f"Accuracy: {accuracy_xgb:.4f}")

"""LightBGM"""

# Train LightGBM model
lgb_clf = lgb.LGBMClassifier(random_state=42)
lgb_clf.fit(X_train_scaled_aug, y_train_aug)

# Predict
y_pred_lgb = lgb_clf.predict(X_test_scaled_aug)
y_pred_labels_lgb = le_aug.inverse_transform(y_pred_lgb)

# Report
print("📊 Classification Report (LightGBM):")
print(classification_report(y_test_labels_aug, y_pred_labels_lgb))

accuracy_lgb = accuracy_score(y_test_aug, y_pred_lgb)
print(f"Accuracy: {accuracy_lgb:.4f}")

"""# EXPORTING BOTH MODELS"""

import joblib

# Save Random Forest classifier components
joblib.dump(clf_aug, 'final_rf_classifier.pkl')

joblib.dump(scaler_aug, 'rf_scaler.pkl')

joblib.dump(le_aug, 'rf_label_encoder.pkl')

joblib.dump(iso, 'isolation_forest_model.pkl')

joblib.dump(db, 'dbscan_model.pkl')

joblib.dump(scaler, 'anomaly_scaler.pkl')

model.save('lstm_autoencoder_model.keras')

from google.colab import files
files.download('final_rf_classifier.pkl')
files.download('rf_scaler.pkl')
files.download('rf_label_encoder.pkl')
files.download('isolation_forest_model.pkl')
files.download('dbscan_model.pkl')
files.download('anomaly_scaler.pkl')
files.download('lstm_autoencoder_model.keras')

